### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by heavysixer** [siuying/node-hearthstone#3]
Hi @siuying,
Would it be possible to add a license file to this repo so that collaborators and contributors know how their code can be used?

Best,
Mark

**Comment by siuying** [comment]
The code is MIT licensed. I have added the LICENSE to repo. Thanks!

**Comment by heavysixer** [comment]
@siuying awesome thanks for doing that. I am really enjoying hacking around on this project while I play Hearthstone.
