### ISSUE TITLE
how does build work?

### ISSUE THREAD

**Issue by heavysixer** [siuying/node-hearthstone#6]
Is there a secret step to getting the build task to work? 
I am working on my stats branch and trying to build it locally to test in game and when I type 
`npm build` the command exits fine but nothing has actually built. 

Thanks,
Mark

**Comment by siuying** [comment]
Does it work if you type `npm run build`?

**Comment by heavysixer** [comment]
no that must have been the problem ;-) i just typed `npm build`
I'll update the README too so that it's clear to new developers like me.
